### ISSUE TITLE
如何跟chatglm-6B结合使用？

### ISSUE THREAD

**Issue by dydwgmcnl4241** [OpenBMB/BMTools#11]

**Comment by thuqinyj16** [comment]
我们会尽快（本周内）实现一个能够load本地版本模型的接口

**Comment by thuqinyj16** [comment]
参考[BMTools](https://github.com/OpenBMB/BMTools/tree/main)/[bmtools](https://github.com/OpenBMB/BMTools/tree/main/bmtools)/[models](https://github.com/OpenBMB/BMTools/tree/main/bmtools/models)
/llama_model.py
