### ISSUE TITLE
python host_local_tools.py this step generate error?

### ISSUE THREAD

**Issue by frankchieng** [OpenBMB/BMTools#12]
when i execute python host_local_tools.py,it appears error as below:
  File "C:\Users\Kurtqian\anaconda3\lib\site-packages\pydantic-2.0a3-py3.8.egg\pydantic\_internal\_generate_schema.py", line 399, in _generate_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'fastapi.openapi.models.EmailStr'>. Setting `arbitrary_types_allowed=True` in the model_config may prevent this error.

For further information visit <TODO: Set up the errors URLs>/schema-for-unknown-type

i just check out the BabyagiTools.py, class Config parameter arbitrary_types_allowed = True already been set, why this error still appears?

**Comment by thuqinyj16** [comment]
Hi can you provide me with your openai and langchain package versions? Mine is 0.27.2 and 0.0.144. Besides, can you provide the full traceback of your error? I need to locate where the bug happens when executing host_local_tools.py

**Comment by frankchieng** [comment]
the above problem solved,but a new one appeared:
when i run the bash python web_demo.py, the error message as below:
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: http://127.0.0.1:7001/startup-events (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000DC6C760>: Failed to establish a new connection: [WinError 10061]

should i have to turn on the local proxy when i run the above bash command?otherwise i can't use any of the plugins, how can i  
config the proxy and run it successfully?

**Comment by Achazwl** [comment]
Probably related to https://stackoverflow.com/questions/33314169/numerous-connectionrefusederror-winerror-10061-in-python-requests
