### ISSUE TITLE
AttributeError: 'ZeroShotAgent' object has no attribute 'prepare_for_new_call'

### ISSUE THREAD

**Issue by lphkxd** [OpenBMB/BMTools#16]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/16346895/234038558-b5772b6a-88fe-4bd0-a7d4-543311e500d8.png">
启动后运行报这个错

**Comment by thuqinyj16** [comment]
b831ca42f0cf2d1e392471f1cf74779c3b51f1ff 应该已经解决，请pull一下BMTools最新的代码
