### ISSUE TITLE
在agent中调用AutoGPT报错如下， 将prompt_type更改为autogpt

### ISSUE THREAD

**Issue by yinyannlp** [OpenBMB/BMTools#17]
Traceback (most recent call last):
  File "/Users/zhenglingxiao/code/BMTools/test.py", line 10, in <module>
    agent("Where is Yaoming Born?")
TypeError: 'AutoGPT' object is not callable

**Comment by yinyannlp** [comment]
请问可以提供支持autogpt的相关文档吗

**Comment by thuqinyj16** [comment]
这两天内我们会更新，可以先把langchain和BMTools都更新到最新的版本，https://github.com/OpenBMB/BMTools/blob/main/test.py这里有使用autogpt的代码

**Comment by thuqinyj16** [comment]
用这个可以执行：agent.run(["write a weather report for SF today"])
