### ISSUE TITLE
Is the evaluation dataset available?

### ISSUE THREAD

**Issue by younghuman** [OpenBMB/BMTools#19]
Hi from the original paper https://arxiv.org/pdf/2304.08354.pdf, it mentioned "pecifically, if humans judge that all the API calls are accurate for the given task, and they yield a reasonable result, the task is deemed to be correctly completed. The codes and our curated dataset will be made available to the academic community"

I'm trying to repeat some of the result, curious if this eval dataset is available somewhere?

**Comment by thuqinyj16** [comment]
Will be released this week.
