### ISSUE TITLE
LLM调用weather插件不成功，"Observation: Use the get_weather_today API is not a valid tool, try another one."

### ISSUE THREAD

**Issue by yuanlelelele** [OpenBMB/BMTools#21]
插件运行：
![image](https://user-images.githubusercontent.com/46896217/234470785-473b101a-0237-4628-94bd-ca68c970f7c4.png)

工具info：
![image](https://user-images.githubusercontent.com/46896217/234471479-80bc92f6-ebe9-49a2-aa75-cd0ba0d9c64e.png)

chain提示信息：
![image](https://user-images.githubusercontent.com/46896217/234471207-eb584e34-016d-4eb5-b008-0500d01ea4e1.png)

帮忙看下是什么原因？

**Comment by thuqinyj16** [comment]
需要模型输出的时候严格保持如下的格式：
Action: ***
Action Input: ***
其中Action后的内容必须只能是API的名字，这里出bug的原因是chatgpt输出了Use the get_weather_today API，Use the和API都是多余的，导致没法parse。解决方案有两个：做更好的prompt engineering让模型输出符合要求，修改parsing方法让其能够支持特殊情况下的action输出

**Comment by yuanlelelele** [comment]
好的感谢。在prompt里对action格式添加说明后，模型输出符合要求了。
