### ISSUE TITLE
插件兼容其他模型的可能性

### ISSUE THREAD

**Issue by SWHL** [OpenBMB/BMTools#22]
感谢开源的项目。我看源码是和openai的key是强绑定的，有考虑过做一个更加独立的版本吗？
比如兼容ChatGLM，MOSS等大模型？

**Comment by Kunlun-Zhu** [comment]
感谢关注，之后有计划兼容CPM-Bee模型，可以参考，https://github.com/OpenBMB/CPM-Live

**Comment by thuqinyj16** [comment]
目前我们也留了一个customllm.py的接口，能够对接llama模型，后续会支持更多本地模型调用

**Comment by SWHL** [comment]
感谢这么快回复，我会持续关注的，可能的话，也会略尽绵薄之力。
