### ISSUE TITLE
Expecting value: line 1 column 1 (char 0).

### ISSUE THREAD

**Issue by arwooy** [OpenBMB/BMTools#23]
No matter which button is clicked on the page, it always reports an error: Something went wrong
Expecting value: line 1 column 1 (char 0).

**Comment by xerrors** [comment]
I have tried Using Single Tool (https://github.com/OpenBMB/BMTools#22-use-a-single-tool), it failed with the RPM limit:

> Thought:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-5uHfrthyQsaRhlJTx3smBKQT on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..

So, pay for it or give up.

**Comment by congxin95** [comment]
Could you provide more detailed error information such as the exceptions raised by the backend?

**Comment by xerrors** [comment]
There is no error in the backend, it should be a JSON parsing problem, because OpenAI’s limit of 3 requests per minute is triggered, the output of the model is not the expected JSON format, but an error text, so `Expecting value: line 1 column 1 (char 0).`

> Could you provide more detailed error information such as the exceptions raised by the backend?

**Comment by congxin95** [comment]
So it seems that your openai-key is limited by OpenAI. You can use another one and try it again. If you have other problem, please let us know to improve this repo. Thank you.

**Comment by xerrors** [comment]
> So it seems that your openai-key is limited by OpenAI. You can use another one and try it again. If you have other problem, please let us know to improve this repo. Thank you.

The Agent in LangChain supports using exponential backoff to retry when the number reaches the limit to avoid interruption. Can we learn from this aspect?
