### ISSUE TITLE
插件反应比较慢，能否支持node脚本？

### ISSUE THREAD

**Issue by MaleWeb** [OpenBMB/BMTools#29]
在多插件下调度的效率有些低，用户关注的往往是结果，最好能加速这个过程。
另外：能够实现类似GPT一样支持多语言插件挂载？

**Comment by thuqinyj16** [comment]
您好，感谢对本项目的关注，请问“多插件下调度的效率有些低”可以给我们一些具体的例子嘛？我们好针对进行优化～

此外“多语言插件挂载”是否指的是让基础模型支持多语言？因为我们模型本身是基于chatgpt API调用的，所以天生是支持多语言的
