### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_chain_start'

### ISSUE THREAD

**Issue by Felix0805** [OpenBMB/BMTools#30]
在我运行web_demo.py时得到了如下报错
<img width="715" alt="image" src="https://github.com/OpenBMB/BMTools/assets/18611373/63a82eb5-8dbd-41d2-bee2-f5b44925edb2">

**Comment by lphkxd** [comment]
langchain==0.0.147 锁到这个版本就可以了
