### ISSUE TITLE
多次调用，自我意想不存在的插件，较高的报错率

### ISSUE THREAD

**Issue by PunkAIGC** [OpenBMB/BMTools#34]
我是用的gpt3.5的key，每次测试都是单插件，插件确保是正常的
1.每当执行命令时，BMTools总是执行两次或多次。例如音乐搜索插件，输入周杰伦，BMTools总会执行两次接口的请求。
![image](https://github.com/OpenBMB/BMTools/assets/133644502/ed574b3c-eddd-4373-8f30-a6ffc1e659b9)
![image](https://github.com/OpenBMB/BMTools/assets/133644502/10a8b502-b7ee-4e2d-88f8-704495ba676a)
![image](https://github.com/OpenBMB/BMTools/assets/133644502/8e1241b2-c9b9-47d5-bc0e-40b2db6f5003)

2.当执行到一次成功的结果后，例如上面的例子已找到答案，但接下来BMTools就开始意想不存在的插件了，这将消耗过多的时间
![image](https://github.com/OpenBMB/BMTools/assets/133644502/36e334d7-4469-49cb-989e-23c42aaded64)

3.在实际使用中，调用10次只有3次是成功的，且耗时在1.5分钟之上。
4.最终答案有时会受到插件介绍的影响，下面最终输出 明显收到了插件介绍的影响（或者插件不支持中文？）
![image](https://github.com/OpenBMB/BMTools/assets/133644502/18ebe05f-f3de-4435-807b-4ea34aed878a)

我非常喜欢OpenBMB的工具，非常感谢你们的付出，也希望插件能够有更好的发展。
上面是我深度体验3天后，发现的问题，希望官方的大佬可以优化并修复，在此再次感谢你们的付出。

**Comment by thuqinyj16** [comment]
感谢提出的issue，我们会近期对您提出的问题进行优化，如果您感兴趣的话，也可以提一个pull request我们共同开发～

**Comment by thuqinyj16** [comment]
模型性能可以进一步通过训练来提升，参考我们的数据集+训练脚本：https://github.com/OpenBMB/ToolBench
