### ISSUE TITLE
Can we use other open-source foundation models？

### ISSUE THREAD

**Issue by submitted-code** [OpenBMB/BMTools#38]
Can we use other open-source foundation models besides ChatGPT？

**Comment by thuqinyj16** [comment]
Yes, GPT 3.5 and 4 are supported by nature. If you want to use other models (e.g., locally hosted ones), please refer to https://github.com/OpenBMB/BMTools/blob/main/bmtools/models/customllm.py

**Comment by zhuchangjiang** [comment]
我改了以后这个测试还是过不了

**Comment by zhuchangjiang** [comment]
![image](https://github.com/OpenBMB/BMTools/assets/26199641/4b9aed76-a3d3-424f-b45d-e952177ac83a)

**Comment by zhuchangjiang** [comment]
![image](https://github.com/OpenBMB/BMTools/assets/26199641/1b29b84d-e114-4539-872f-4693ddd50075)

**Comment by zhuchangjiang** [comment]
就是这个地方咋改

**Comment by thuqinyj16** [comment]
https://github.com/OpenBMB/ToolBench
这里有使用本地训练出来的llama接入BMTools的代码
