### ISSUE TITLE
Operating Environment

### ISSUE THREAD

**Issue by dawan1987** [OpenBMB/BMTools#49]
Hello, I am a beginner who has just started learning about Tool Learning. I have used CentOS 7 and CentOS Stream 9 to install and run the environment, but I always encounter various errors when installing related dependencies, which makes it difficult for me to complete deployments. Therefore, I would like to ask which version of operating system environment do you use?

**Comment by thuqinyj16** [comment]
Linux, Windows, or Mac is fine.
