### ISSUE TITLE
请问如何集成llama?

### ISSUE THREAD

**Issue by rivergao87** [OpenBMB/BMTools#59]
粗看代码，agent代理的openai，请问怎么集成llama呢？llama2源代码和llama几乎一样，是不是集成工作量也接近？非常感谢！

**Comment by thuqinyj16** [comment]
您好，只要修改https://github.com/OpenBMB/BMTools/blob/main/bmtools/models/llama_model.py 代码即可

**Comment by rivergao87** [comment]
是否需要配置 openai key?

**Comment by thuqinyj16** [comment]
不需要的

**Comment by rivergao87** [comment]
solved

**Comment by rivergao87** [comment]
- [ ]

**Comment by rivergao87** [comment]
- [ ]
